### ISSUE TITLE
Need feedback from developer on design concepts

### ISSUE THREAD

**Issue by mattriopelle** [LiftUX/IssuePress#10]
Please review and offer any feedback on the wireframe concepts posted: https://asset1.basecamp.com/1761770/projects/1471317-issue-press/attachments/27191115/Issue-press-prototypev2.0.zip

**Comment by mattriopelle** [comment]
If you need me to schedule a meeting with @imbradmiller, so that he can cover the highlights, let me know.

**Comment by imbradmiller** [comment]
I'm game if necessary! I give free hugs as well.

**Comment by matthewsimo** [comment]
I'll post here after I get some time to look over it if a scheduled meeting is required. If not a simple skype chat/email might suffice for any questions.

**Comment by imbradmiller** [comment]
Great. Thank you, sir.

**Comment by mattriopelle** [comment]
I thought hugs were a punishment.

**Comment by imbradmiller** [comment]
My bear hug is! But my teddy bear hug is a privilege.

**Comment by imbradmiller** [comment]
I'm not sure if I want to close this. Simo, did you want to provide some feedback here and we'll review your thoughts on the designs?

**Comment by matthewsimo** [comment]
I believe we already got together on skype & handled this. My feedback was taken into account as I remember and was moved on to @garand for prototyping. Closing out.
