### ISSUE TITLE
Issue Listing Widget

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#110]
A simple widget that show the list of issues rather than having the user just search for issues.

**Comment by matthewsimo** [comment]
I'm working on wiring up the API integrations for this but would it be possible to get a wireframe for how this should look client side?

**Comment by imbradmiller** [comment]
I can do that, Simo. Taking this on.

**Comment by imbradmiller** [comment]
This is from @calebsylvest's assessment.

Open and Closed Issues. Need a listing of all Open issues and Closed issues. This will provide an archive of searchable issues that will reduce the amount of support request (or should), preventing people from submitting the same request again and again.

Maybe we can make something on this widget that allows a users to see open and or closed issues.

**Comment by matthewsimo** [comment]
Yes, that was the purpose of this widget, even perhaps a filterable
mini-nab that would only show what was selected. This widget is still
largely dependent on the wireframe - what’s the status of that Brad?

On Fri, May 23, 2014 at 1:05 PM, Brad Miller notifications@github.comwrote:

> This is from @calebsylvest https://github.com/calebsylvest's assessment.
> 
> Open and Closed Issues. Need a listing of all Open issues and Closed
> issues. This will provide an archive of searchable issues that will reduce
> the amount of support request (or should), preventing people from
> submitting the same request again and again.
> 
> Maybe we can make something on this widget that allows a users to see open
> and or closed issues.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/UpThemes/IssuePress/issues/110#issuecomment-44042253
> .

## 
- Matthew Simo

**Comment by imbradmiller** [comment]
@matthewsimo, I suck and haven't done it yet. After I get these features organized I'll start on that.

**Comment by matthewsimo** [comment]
No worries, you do you.

On Fri, May 23, 2014 at 2:01 PM, Brad Miller notifications@github.comwrote:

> @matthewsimo https://github.com/matthewsimo, I suck and haven't done it
> yet. After I get these features organized I'll start on that.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/UpThemes/IssuePress/issues/110#issuecomment-44048432
> .

## 
- Matthew Simo

**Comment by imbradmiller** [comment]
![screen shot 2014-06-05 at 4 19 46 pm](https://cloud.githubusercontent.com/assets/390916/3193142/f78f7c36-ecee-11e3-9f6d-ee651b0575f0.png)
- Filter option that allows a users to filter support requests either by closed, open or all
- Issue # in title
- Title and number links to issue
- Label that shows the issue status

**Comment by imbradmiller** [comment]
Looks good functionality wise, just need to have a few content items add for usability.

On the widget when there are no issues, we need to come up with a more accurate message for the user. See this screenshot.
![screen shot 2014-06-27 at 12 51 13 pm](https://cloud.githubusercontent.com/assets/390916/3415029/5e569a38-fe1c-11e3-9359-e9b9dff5f980.png)

When there are no closed issues, there is no message for the user stating this. See this screenshot.
![screen shot 2014-06-27 at 1 01 28 pm](https://cloud.githubusercontent.com/assets/390916/3415061/bcc060f4-fe1c-11e3-9c8c-95b73119eb29.png)

This should be good to go once those are fixed.

**Comment by matthewsimo** [comment]
I updated fixes for both of the issues you raised. I've also fixed the default install widget title to "Support Requests" to fall inline with that previous change as well. Let me know if it's ready to go or if you notice anything else! Thanks @imbradmiller

**Comment by imbradmiller** [comment]
This looks good, Simo. Thanks. Marking for deployment.
