### ISSUE TITLE
Customization of IssuePress Plugin Interface

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#111]
@chriswallace 

Please define the requirements for this.

**Comment by imbradmiller** [comment]
- [x] Logo - Users should be able to upload their own logo for the IP header
- [x] Color Schemes - Users should be able to customize the color scheme for all major parts of the IP plugin.

**Comment by matthewsimo** [comment]
Where should we put this into the app?

Options I see are:
- Just lump it in with the current settings page, add it underneath
- New Admin Page under the IssuePress Block in Admin Menu
- New tab on the main IssuePress settings page, (would require creating a tab for "Settings" - for current page & "Customization" for these two options)

While we're cleaning up, it might not be a bad idea to move the "License Key" admin page content to under the main settings either.. Though, I'd have to check if EDD gives us the ability to add that wherever we want to.

Thoughts? What makes the most sense?

**Comment by matthewsimo** [comment]
I think I'm leaning towards restructuring down to one admin page, with two tabs, "Settings" & "Customizations".

**Comment by chriswallace** [comment]
You're welcome to consolidate things. I just used the example EDD setup and kept it on its own page to keep it simple for launch. I think a tab approach is ideal.

**Comment by matthewsimo** [comment]
Cool, I'll work on converting this over to tabs then.

**Comment by imbradmiller** [comment]
Tested this and it's in good shape.

**Comment by chriswallace** [comment]
Nullam quis risus eget urna mollis ornare vel eu leo. Donec id elit non mi porta gravida at eget metus. Donec ullamcorper nulla non metus auctor fringilla. Aenean lacinia bibendum nulla sed consectetur. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.

---

IssuePress Data:

username: calebsylvest
email: caleb@liftux.com
firstname: Caleb
lastname: Sylvest
display_name: Caleb Sylvest
ID: 11
gravatar_id: 596e827e2287f293f161935c53214cd4

Sent via [IssuePress](http://issuepress.co)
