### ISSUE TITLE
Label System Addition

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#113]
Incorporate the ability to add labels and or manage labels from IssuePress interface.

Requirements to be defined in more detail.

**Comment by imbradmiller** [comment]
We need to get this going ASAP, We need the ability to have issues that have the "issue press" label be displayed only on the issue press plugin.

**Comment by matthewsimo** [comment]
Should we only pull in the IssuePress or should we allow users to create their own blacklist label?

**Comment by imbradmiller** [comment]
Good question. Going to bring this up in our call now.

**Comment by imbradmiller** [comment]
Key Decision: We want to develop this that will only display issues that are labeled with "IssuePress".
