### ISSUE TITLE
First pass on design due

### ISSUE THREAD

**Issue by mattriopelle** [LiftUX/IssuePress#12]
Can you have this by Wednesday, @garand?

**Comment by mattriopelle** [comment]
I'll give you one until Wednesday, 3/20, or I shall smite you.

**Comment by mattriopelle** [comment]
Consider yourself smited. ;)

**Comment by garand** [comment]
My week in Dallas consisted of a lot of work on the new Lift site, so I wasn't able to spend time on this. I'll see what I can get to in the next few days, and will update you again on Friday.

**Comment by mattriopelle** [comment]
Thanks amigo. I will look for something Friday.

**Comment by garand** [comment]
First pass through is pushed.

http://issuepress-web.herokuapp.com/

**Comment by mattriopelle** [comment]
Thanks Anthony!
