### ISSUE TITLE
Select repository message appeared twice

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/IssuePress#120]
The first time configuring IssuePress the "Please select one or more repositories to complete IssuePress setup" message box appeared twice on the page.

I selected a repository then deleted it and saved and the message only appeared once from then on.

---

IssuePress Data:

username: douglsmith
email: doug@smithsrus.com
firstname: Doug
lastname: Smith
display_name: Doug Smith
ID: 23
gravatar_id: 141ced34d36b08ae93437bc019265374

Sent via [IssuePress](http://issuepress.co)

**Comment by imbradmiller** [comment]
Doug,

Is this still happening for you? I could not recreate this issue. Closing for now.

Thanks,
Brad
