### ISSUE TITLE
My First Issue

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/IssuePress#125]
Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Sed posuere consectetur est at lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue. Vestibulum id ligula porta felis euismod semper. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.

---

IssuePress Data:

username: calebsylvest
email: caleb@liftux.com
firstname: Caleb
lastname: Sylvest
display_name: Caleb Sylvest
ID: 11
gravatar_id: 596e827e2287f293f161935c53214cd4

Sent via [IssuePress](http://issuepress.co)

**Comment by issuepressapp** [comment]
ok

---

IssuePress Data:

username: "benfavre"
email: "ben@webdesign29.net"
firstname: ""
lastname: ""
display_name: "benfavre"
ID: "114"
gravatar_id: "306b83436a7d0d972007bf2daebf51fd"

Sent via [IssuePress](http://issuepress.co)
