### ISSUE TITLE
Closed issues need a ‘Closed’ badge if appearing in the Recent Activity thread

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#132]
From @calebsylvest's assessment.

Closed issues need a ‘Closed’ badge if appearing in the Recent Activity thread.

We will need a design for this.

**Comment by matthewsimo** [comment]
I figure we'll be coming up with issues more like "Recent Activity WIdget Improvements" and having a list of check items, one of which this would be.. I figure we'll need to do one for each widget in turn.

**Comment by imbradmiller** [comment]
I'll take this on.
