### ISSUE TITLE
Need to investigate how we can clean up the navigational parts of IP

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#133]
From @calebsylvest's assessment.

What repo am I in? Repo Name should be dominant (H1). Breadcrumbs may not be necessary, 1. we are duplicating globally available links from the page navigation 2. there could be an instance where an IssuePress user wants to circumvent the Dashboard and Support Sections pages and focus customers on the Repo Page.

We just need to define this as a rule and I'm going to assign this @calebsylvest for now to define this UX.

**Comment by imbradmiller** [comment]
I'll take this one on.

**Comment by chriswallace** [comment]
This may still be an issue but now that we have a new design, I think we should create a new issue to address revamping the way "IssuePress Sections" work.

**Comment by matthewsimo** [comment]
Agreed
