### ISSUE TITLE
Issue Template Header Enhancements

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#134]
From @calebsylvest's assessment. 

Needs a Large page header with H1 of the Title of the Issue (currently Title of the issue is not even used). H1 area should also include the issue # and Status (open or closed). Reference Github.

This needs a design.

**Comment by calebsylvest** [comment]
Here is a wireframe doodle of the page header, page headers should follow the same basic template structure whether they are for 'Repo' pages or 'Issue' pages.

```
-----------------------------------------------------

   Repo Name

-----------------------------------------------------

-----------------------------------------------------
    Repo Name
<  The Issue Title #00
    Created: May 12, 2014    [ ] tag tag tag
-----------------------------------------------------
```

![ip-issue-page](https://cloud.githubusercontent.com/assets/4457883/3072152/b9f409f4-e2c2-11e3-8e39-02dc04b1de61.jpg)

**Comment by calebsylvest** [comment]
@garand let me know if this makes sense or needs more explanation.

**Comment by garand** [comment]
This looks good Caleb. I'll start working on this today and I will have updates to look at early next week, if not sooner.

**Comment by garand** [comment]
This is going to be rolled in with the other mobile/foundation updates. @imbradmiller Can you create that?

@matthewsimo Can you confirm that the items referenced in @calebsylvest's mockup are present in the markup?

**Comment by matthewsimo** [comment]
I thought the goal was to do this piece mail, so that you can focus on a manageable pieces between retainer/upthemes work.. So, while it's "under" the mobile/foundation updates, all that work doesn't have to wait for one massive merge..

**Comment by garand** [comment]
True. I'll connect with you when I get a chance to get started on IssuePress as a whole.

**Comment by imbradmiller** [comment]
Is this issue obsolete now with Chris's updates?
