### ISSUE TITLE
Change 'Issue' terminology to 'support request' on front-end

### ISSUE THREAD

**Issue by issuepressapp** [LiftUX/IssuePress#135]
Wherever we use the term 'issue' on the front-end of the app, the user should only ever see the term 'support request.'

---

IssuePress Data:

username: chriswallace
email: chris@liftux.com
firstname: Chris
lastname: Wallace
display_name: Chris Wallace
ID: 1
gravatar_id: de5e8c95f06ac55e9b297c7c3e1de33b

Sent via [IssuePress](http://issuepress.co)

**Comment by imbradmiller** [comment]
Looks good.
