### ISSUE TITLE
Define Mobile Strategy

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#138]
Put together a strategy for mobile responsive work. Create a punch list so that we can track progress.

**Comment by garand** [comment]
I talked with @matthewsimo, we're going to give Foundation a shot. It will take a substantial amount of time to transition the templates over, but hopefully it will be worth it in the long run. Once I can get the UpThemes tickets out of the way I should be able to start on this. This will also encompass #70. Sometime next week, maybe Wednesday after I get AMC and UpThemes out of the way, I'll put together a list of the templates that will need to be completed while I'm working on this. Probably as a nested task list inside of another ticket or pull request. Feel free to provide any comments about Foundation or other items I should keep in mind when putting together the list on this ticket.

**Comment by chriswallace** [comment]
@matthewsimo @garand Sounds good. Will you be importing Foundation as a dependency in the Compass config or via Grunt/Libsass? Also, which modules do you envision using right off the bat?

**Comment by garand** [comment]
I'm not sure yet, @matthewsimo do you have any suggestions on that front?

**Comment by imbradmiller** [comment]
@garand that sounds good. Thanks for getting a plan of action in order. As we discussed I think it's important that we focus only on the minimal stuff. We can always add things back in when necessary. I think we could quickly meet and go over the things that are necessary. Let me know.

**Comment by matthewsimo** [comment]
I'm unfamiliar with Foundation usage and any requirements/conflicts it raises in regards to our set up. Since we don't know/control the environment that IP runs in we should go with the safest. I was relying on Anthony's input since he was looking into using it..
