### ISSUE TITLE
Do User Need to Have a Github Username?

### ISSUE THREAD

**Issue by issuepressapp** [LiftUX/IssuePress#148]
So... because this support question will be submitted to Github issues page also, how do you sync submitter user in this support section and Github issues page? 

Do User Need to Have a Github Username?

---

IssuePress Data:

username: "agusmu"
email: "business@agusmu.com"
firstname: "Agus"
lastname: "MU"
display_name: "Agus MU"
ID: "153"
gravatar_id: "67897c1e1b68bab9feda31713f8d5bb0"

Sent via [IssuePress](http://issuepress.co)

**Comment by imbradmiller** [comment]
Hi Agus,

As of right now a user does not need a GitHub account to interact with the app. We only grab their username from the WordPress user and place it within a comment of the issue in GitHub. If you are the owner of the repo, you will need a GitHub account. Let me know if you have any other questions.

Thanks,
Brad
