### ISSUE TITLE
Github to WordPress

### ISSUE THREAD

**Issue by issuepressapp** [LiftUX/IssuePress#149]
Hi guys. I'm really looking forward to testing this bad boy out - Jeffro says its the one! 

Can you confirm that issuepress will provide a way for us to easily sync all github issues aka this:

https://github.com/gamelab/kiwi.js/issues/43#issuecomment-49820702

... including comments on our kiwijs.org website? 

The point of this for exercise for us is to create an environment for deep and meaningful developer conversations on our website as well as on github... but mostly on our website :)

---

IssuePress Data:

username: "danmilward"
email: "dan@instinct.co.nz"
firstname: "Dan"
lastname: "Milward"
display_name: "Dan Milward"
ID: "200"
gravatar_id: "5ba89a2ce585864ce73cafa7e79d114c"

Sent via [IssuePress](http://issuepress.co)

**Comment by imbradmiller** [comment]
Hi Dan,

Thanks for the questions and the excitement. That is correct all issues created from within the IssuePress plugin are synced with both GitHub and IssuePress. You can also create issues in GitHub, then mark them with the "issuepress" label and they will display in the IP plugin. 

Let me know if there are any other questions I can answer.

Thanks,
Brad
