### ISSUE TITLE
White screen fatal error when trying to set up GitHub credentials

### ISSUE THREAD

**Issue by issuepressapp** [LiftUX/IssuePress#151]
When trying to set up after step 9 of instructions my site crashed (white screen). Here is what one of our devs said to submit to your support...
Thanks.

The white screen is a fatal error being caused by the fact that you have not entered valid credentials for Github (and apparently IssuePress does not have proper error handling for this sort of thing). You should feel free to submit a ticket to them, explaining that they should catch the following exception Fatal error: Uncaught exception 'Github\Exception\RuntimeException' with message 'Bad credentials' in /data/www/wordpress/wp-content/plugins/issuepress/vendor/knplabs/github-api/lib/Github/HttpClient/Listener/ErrorListener.php:85 and give a proper error message.

---

IssuePress Data:

username: "cyrijones"
email: "cyrijones@zenportfolios.ca"
firstname: "Cyri"
lastname: "Jones"
display_name: "Cyri Jones"
ID: "213"
gravatar_id: "08acde153f5d99fd8bb11b2aad4ecf72"

Sent via [IssuePress](http://issuepress.co)

**Comment by chriswallace** [comment]
Thanks for reporting this, we will take a look at this and let you know how to proceed.
