### ISSUE TITLE
GitHub profile image does not match

### ISSUE THREAD

**Issue by issuepressapp** [LiftUX/IssuePress#154]
I noticed that my GitHub profile image is not loading the same when commenting to an issue.

See screenshots - https://cloudup.com/cYnOg2tBTyS

---

IssuePress Data:

username: "seb86"
email: "mailme@sebastiendumont.com"
firstname: "Sebastien"
lastname: "Dumont"
display_name: "Sebastien Dumont"
ID: "32"
gravatar_id: "c3f9be587ccc8656bad714cb945f70a4"

Sent via [IssuePress](http://issuepress.co)

**Comment by chriswallace** [comment]
hkhkhjkj

---

IssuePress Data:

username: "liftux"
email: "chris@liftux.com"
firstname: "Chris"
lastname: "Wallace"
display_name: "Chris Wallace"
ID: "2"
gravatar_id: "de5e8c95f06ac55e9b297c7c3e1de33b"

Sent via [IssuePress](http://issuepress.co)
