### ISSUE TITLE
Post Activation WordPress Notice

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#158]
Need a notification for users when they activate the plugin.
![screen shot 2014-10-06 at 12 13 35 pm](https://cloud.githubusercontent.com/assets/390916/4529005/e84da7ee-4d73-11e4-8056-14d7bfe9aea9.png)

**Comment by issuepressapp** [comment]
What notification? Please explain the requirement.

On Monday, October 6, 2014, Brad Miller notifications@github.com wrote:

> Need a notification for users when they activate the plugin.
> [image: screen shot 2014-10-06 at 12 13 35 pm]
> https://cloud.githubusercontent.com/assets/390916/4529005/e84da7ee-4d73-11e4-8056-14d7bfe9aea9.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UpThemes/IssuePress/issues/158.

## 

Chris Wallace
Principal Creative // Lift

mobile 314-406-9109
skype chriswallace7
email/gtalk chris@liftux.com

http://liftux.com
