### ISSUE TITLE
What happens when you follow an issue?

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#16]
What happens when you follow and issue? Does the style change (I would assume so) or just the text?

**Comment by garand** [comment]
I'm not sure. I don't believe we have decided on that.

We could just have a badge display whenever the issue is displayed to identify that it has been followed. Maybe we could change following, to starring? Then we could display a filled in star icon next to the issue.

@matthewsimo What do you think?

**Comment by matthewsimo** [comment]
I guess we first need to define what context are you asking about.. Within search results I think it would be useful. In widgets and other contexts, perhaps not as useful -- and even harmful in some cases.

I'm a little out of the loop on this project so unfortunately I can't give too much valuable input. I'll leave in your guy's capable hands..

**Comment by imbradmiller** [comment]
I think we just have the style change like twitter. Following, Not Following. That easy. Let's not get crazy with it.

**Comment by garand** [comment]
Do we want to only toggle this "Follow" text?

![image](https://f.cloud.github.com/assets/82437/431377/0fa88dc8-ae87-11e2-9d4e-72ad976d809d.png)

Or should we display the follow status in other contexts as well?

**Comment by imbradmiller** [comment]
I'm not following the "Or should we display the follow status in other contexts as well?" Do you mean in other areas of the site that we are following thread? I think it should be Follow and Unfollow fro the text. Just my personal thought on that matter.

**Comment by garand** [comment]
I mean if we display the thread in a list elsewhere on the site, for instance "Recently active threads" should we display if the user follows them in that list?

**Comment by imbradmiller** [comment]
I would think so.

**Comment by garand** [comment]
Added this in fce9361b3bb2b1db2a2ab644170e434c37caaac2

The functionality should work as follows.

If you are following a section, the button will say "Following". On hover the text will change to "Unfollow".

If you are not following a section, the button will say "Follow", once clicked it will take on the behavior of followed sections.

![image](https://f.cloud.github.com/assets/82437/444728/fc940010-b1aa-11e2-914e-f1c55d2f13f8.png)

This behavior will act the same for following/unfollowing within a thread.

![image](https://f.cloud.github.com/assets/82437/444737/1b7ac61c-b1ab-11e2-96db-eaab8157824f.png)
