### ISSUE TITLE
Downloading latest version

### ISSUE THREAD

**Issue by issuepressapp** [LiftUX/IssuePress#163]
Hello. Where can I download the latest version of this plugin?
Thanks.

---

IssuePress Data:

username: "cyrijones"
email: "cyrijones@zenportfolios.ca"
firstname: "Cyri"
lastname: "Jones"
display_name: "Cyri Jones"
ID: "213"
gravatar_id: "08acde153f5d99fd8bb11b2aad4ecf72"

Sent via [IssuePress](http://issuepress.co)

**Comment by matthewsimo** [comment]
Hi Cyri,

We're [reworking IssuePress](http://issuepress.co/2014/08/22/new-direction-issuepress/) to be a lot better and fit a lot of various workflows. While we're working hard on it, we've taken the download link down for the time being. Keep an eye out, we'll communicate when we submit IssuePress to the WordPress Plugin Repository. Thanks for you interest in IssuePress!
