### ISSUE TITLE
Support Form Shortcode Validation

### ISSUE THREAD

**Issue by ataylorme** [LiftUX/IssuePress#166]
The form generate by `[ip_support_form]` does not have any validation.

As a result empty support requests can be submitted.

I would suggest adding basic server side form validation with PHP.

The docs can be updated to reflect that user's are welcome to add their own form validation, such as JavaScript validation, and the PHP validation will remain as a fall-back.

![screen shot 2014-10-09 at 2 29 24 pm](https://cloud.githubusercontent.com/assets/2133004/4582921/f9c1269c-4fec-11e4-809a-cbafddbaa851.png)
![screen shot 2014-10-09 at 2 29 29 pm](https://cloud.githubusercontent.com/assets/2133004/4582922/f9c408d0-4fec-11e4-9301-8c9df1ed5ba3.png)

**Comment by matthewsimo** [comment]
Thanks for catching this - supposed to be throwing an error on empty titles. Will take a look.

**Comment by matthewsimo** [comment]
I've abstracted and added enhancements to the error handling within the plugin. I've fixed the support form handler's validation in the process as well. Closing out for now, we can reopen if things need tweaking or twerking.
