### ISSUE TITLE
Support Sections Listing Template/Module

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#17]
In the wires we created a template that was the listing of support sections. It looks like the attached.
![Screen Shot 2013-04-22 at 2 45 12 PM](https://f.cloud.github.com/assets/390916/410926/d04953b8-ab7c-11e2-8b8c-18d0c501266e.png)

**Comment by garand** [comment]
We will be reusing the sidebar module for this. It can be styled differently based on its context.

![image](https://f.cloud.github.com/assets/82437/427755/c92c2d8e-adee-11e2-867d-718ee68c8713.png)
