### ISSUE TITLE
Base wireframe for the_content default

### ISSUE THREAD

**Issue by matthewsimo** [LiftUX/IssuePress#170]
Need simple wireframe for the_content for support requests singles. Specifically placement of meta data stuff.

**Comment by imbradmiller** [comment]
@chriswallace,

Can you get to this today?

Thanks,
Brad

**Comment by imbradmiller** [comment]
Chris Wallace [10:52 AM] 
hey guys, I'm cleaning stuff up for Largo but will jump on this (IssuePress) when I'm done

**Comment by chriswallace** [comment]
@matthewsimo Please get @calebsylvest up to speed on what we need for this. I won't have time to address this for a while.

**Comment by imbradmiller** [comment]
@calebsylvest and @matthewsimo, since @chriswallace will not be available for the rest of the week. We'll need to make this a priority tomorrow. Let's have a quick check in tomorrow to get this shifted.

**Comment by matthewsimo** [comment]
@calebsylvest Here are some background links:

The template for support meta is here: https://github.com/UpThemes/IssuePress/blob/master/templates/support-meta.php

The related commit for filtering the_content on support requests: https://github.com/UpThemes/IssuePress/commit/5660645edced99bab038af13ad124a2e868280d0

Thanks!

**Comment by matthewsimo** [comment]
I completed and pushed this to master yesterday.
