### ISSUE TITLE
Assets for IssuePress for WordPress Plugin Directory

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#172]
We need to get a few assets created for the plugin that will be living in the WordPress.org Plugin directory. You can find more details about the process here https://wordpress.org/plugins/about/faq/
- [x] Icon
- [ ] Screenshots
- [x] Banners

**For Screenshots**
Screenshot image files should ideally be put in the assets/ directory (which you may need to create) in the root of your SVN checkout. This will be on the same level as tags/ and trunk/, for example. Alternatively, screenshots can be put in the directory of the tagged stable release (trunk/ or the stable tag directory) (the old way). The assets/ directory is preferred since the screenshots won't be packaged in the plugin's release zip files, saving unnecessary bloat for each download. Learn more from the feature's announcement post.

**For Banners**
How do I make one of those cool banners for my plugin page?

Start by creating an assets/ directory in the root of your SVN checkout (if one doesn't already exist). This will be on the same level as tags/ and trunk/, for example.

Inside that assets/ directory, you can make a file named "banner-772x250.png" or "banner-772x250.jpg". The image must be exactly 772 pixels wide and 250 pixels tall. No GIFs.

To support high-DPI (aka "retina") displays, you can additionally make a file named "banner-1544x500.png" or "banner-1544x500.jpg". The image must be exactly 1544 pixels wide and 500 pixels tall. No GIFs. This image, if present, will only be served when the website detects that the viewing browser is on a high-DPI display. Read this feature's announcement post for more details and special notes about creating this image.

After you check in your new banner(s), it will appear the next time the plugin refreshes itself in the directory. This may take a few minutes.

For development and testing, you can add a URL parameter to your plugin's URL of "?banner_url=A_URL_TO_YOUR_IMAGE" to preview what the page will look like with your own image. This will only work with your own plugins; you cannot use this parameter on anybody else's plugins.

**Comment by calebsylvest** [comment]
Found this for icon: https://make.wordpress.org/core/2014/08/21/introducing-plugin-icons-in-the-plugin-installer/

Plugin icons are 128 pixels square. HiDPI (retina) icons are supported at 256 pixels square. Like banners, these go into your /assets directory and can be either a PNG or JPG. So just create assets/icon-128x128.(png|jpg) and/or assets/icon-256x256.(png|jpg) and you have an icon.

**Comment by calebsylvest** [comment]
The assets for the plugin can be found on google Drive, here:

/Google Drive/Lift Team Folder/Internal Projects/IssuePress/Design/Plugin Design/assets/...

There's an .svg file in with the other images in Google Drive, but Github doesn't allow svg image attachments:

![banner-772x250](https://cloud.githubusercontent.com/assets/4457883/4834617/498ad840-5faf-11e4-9f6f-d7b90ce7ac2e.jpg)
![banner-1544x500](https://cloud.githubusercontent.com/assets/4457883/4834615/49842824-5faf-11e4-96bc-71d40a6c32c4.jpg)
![icon-128x128](https://cloud.githubusercontent.com/assets/4457883/4834614/49827c0e-5faf-11e4-915c-5aa40b1de804.png)
![icon-256x256](https://cloud.githubusercontent.com/assets/4457883/4834616/498970ae-5faf-11e4-884c-e30e376dd3f2.png)

**Comment by matthewsimo** [comment]
Thanks Caleb.
