### ISSUE TITLE
Any progress?

### ISSUE THREAD

**Issue by dovy** [LiftUX/IssuePress#178]
Things seemed to have died down. Is this still being developed?

**Comment by chriswallace** [comment]
We've put things on hold for the holidays, but the official plugin is currently in the .org repo: http://wordpress.org/plugins/issuepress/

**Comment by dovy** [comment]
That's what I thought. Still the angular version I see. Any word on the PHP?

**Comment by chriswallace** [comment]
The new version is on github

On Wednesday, November 26, 2014, Dovy Paukstys notifications@github.com
wrote:

> That's what I thought. Still the angular version I see. Any word on the
> PHP?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UpThemes/IssuePress/issues/178#issuecomment-64721103.

## 

Chris Wallace
Principal Creative // Lift

mobile 314-406-9109
skype chriswallace7
email/gtalk chris@liftux.com

http://liftux.com

**Comment by dovy** [comment]
Yea, just tried it out. Getting JS errors. Not functional then?
