### ISSUE TITLE
So, where does one actually download this thing?

### ISSUE THREAD

**Issue by kprovance** [LiftUX/IssuePress#179]
And I mean the proper version that integrates with Github, not the barely functioning thing on wp.org?

**Comment by kprovance** [comment]
Helpful.

**Comment by chriswallace** [comment]
@kprovance Sorry, the project has been shut down for quite some time now. I can't promise that it even works but the last working version is here: https://github.com/LiftUX/IssuePress/archive/ng-ip.zip
