### ISSUE TITLE
Search results style

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#20]
Need to have search results style like attached.
![Screen Shot 2013-04-22 at 3 42 30 PM](https://f.cloud.github.com/assets/390916/411254/e2fb3a82-ab84-11e2-893c-3ba5abd9e93d.png)

**Comment by garand** [comment]
I thought we were going to have a live search box, and therefore not have a dedicated search page. What do you think @imbradmiller @matthewsimo?

**Comment by imbradmiller** [comment]
yes, that's what I'm talking about. it would update the results in the main content area. If this was duplicated we can close.

**Comment by garand** [comment]
This is related to #21
