### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#28]
- [x] Setup and Install
- [ ] GitHub Daemon Account
- [ ] App Configuration
- [x] Development Documentation

**Comment by imbradmiller** [comment]
Cutting this from beta.
- [ ] Sidebar Configuration

**Comment by imbradmiller** [comment]
@matthewsimo, I'll probably need you to help with the GitHub Daemon account instructions.

**Comment by matthewsimo** [comment]
@imbradmiller let me know if you need any help on this or if there is still documentation still left to do - otherwise might be good to close down for now and open any changes or section changes to their own issue for further development.

**Comment by imbradmiller** [comment]
I think if you want to review the documentation that we currently have and make any notes of things we may still need, that would be helpful. I'm currently working on a few things and It may help us out to know if there is anything we are missing.
