### ISSUE TITLE
Find suitable Google Font to replace Proxima Nova & package with prototype

### ISSUE THREAD

**Issue by matthewsimo** [LiftUX/IssuePress#30]

**Comment by chriswallace** [comment]
This one is probably fine: www.google.com/webfonts/specimen/Open+Sans

**Comment by imbradmiller** [comment]
Going with the suggestion Chris and Simo provided. Make it so, Simo.

**Comment by imbradmiller** [comment]
Where are we with this task? Can we close this out?

**Comment by matthewsimo** [comment]
Yes, we can close out, it's already been replaced in the plugin
