### ISSUE TITLE
Markup/styles for Sections Template 

### ISSUE THREAD

**Issue by matthewsimo** [LiftUX/IssuePress#32]
Yo, @garand didn't see these anywhere in the prototype, wondering if I'm looking in the wrong place or if they are still in the works. You can see this page covered in the specs document at '1.4'. Thanks

**Comment by garand** [comment]
Probably hasn't been completed. @imbradmiller, was this in the wireframe? If someone can mockup how it should look, I can do the markup and styles in the next day or so.

**Comment by imbradmiller** [comment]
If it was in the spec, it was in the wireframe. ;)

Let's get this done asap. We were supposed to be completed with this stuff as to not hold Simo up. GOSH! (http://www.youtube.com/watch?v=U_54TT-_h14)

**Comment by garand** [comment]
Ok, can you send me a screenshot of how it looks in the wireframe and I can get it taken care of?

**Comment by imbradmiller** [comment]
![image](https://f.cloud.github.com/assets/82437/782176/994ca61e-ea36-11e2-8ad2-6a542633e562.png)

**Comment by garand** [comment]
@matthewsimo Is that the section you are referring to? That does not look like what is defined in 1.4.

**Comment by matthewsimo** [comment]
@garand Perhaps you're looking at v1, in v2 it is subsection 1.4 -
http://mas.im/QByV

On Thu, Jul 11, 2013 at 9:31 AM, Anthony Garand notifications@github.comwrote:

> @matthewsimo https://github.com/matthewsimo Is that the section you are
> referring to? That does not look like what is defined in 1.4.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LiftUX/IssuePress/issues/32#issuecomment-20815399
> .

## 
- Matthew Simo

**Comment by imbradmiller** [comment]
Where are we with this task?

**Comment by matthewsimo** [comment]
Pushing this over to @calebsylvest, might still wanna follow up to see if @garand was able to start addressing this stuff. Thanks!

**Comment by calebsylvest** [comment]
This is completed. Some reason the Github app didn't close for me on commit.
