### ISSUE TITLE
Look into easy digital downloads and all the extensions that we will need

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#33]

**Comment by matthewsimo** [comment]
Should this exist on the IssuePress-Site, since I figure it'd be apart of that? Or am I off?

Just not sure, since this repo is specifically for the shippable plugin.

**Comment by imbradmiller** [comment]
To be honest, I'm not sure of that. @chriswallace ?

**Comment by imbradmiller** [comment]
@chriswallace is the issue between the Plugin and license server related to this ticket? Let me know if a new ticket should be created.

**Comment by chriswallace** [comment]
This has been set up and is now working properly.
