### ISSUE TITLE
Plugin Options Panel Updates

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#41]
- [ ] Design the process for initial plugin setup.
- [x] Oauth integration in place of username/password.
- [ ] Allow user to select organization repos, not just personal repos.
- [ ] Add support for changing name of repo.
- [ ] Add option for changing name of 'Support Sections' title.

**Comment by chriswallace** [comment]
Let's close this out and we can open new issues for each bullet point as needed.
