### ISSUE TITLE
Do an assessment of what is left for development.

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#53]
- [x] Create punch list of items that need to be completed.
- [x] Define estimated level of effort for items
- [x] Create GitHub tasks OR assign to @imbradmiller for creation of tasks

**Comment by matthewsimo** [comment]
Hi, sorry it's taken this long to get this compiled. 

#### Items to be completed for internal testing:
- Finish the widgets, estimated time, 1.5 hours. #29 
- Send all the data to the client on initial load, or trigger fetching all data on initial load but quickly after load get from IP_api. ~ 2-3 hours #55 
- Create global context angular service, which kind of ties everything together for the entire app. Allows for easy binding of data to various scopes throughout each template. ~ 4-6 hours #56 
- Finish & Hook up the search widget, ~8 hours #57

**Comment by matthewsimo** [comment]
Closing as all tasks are completed and related items have tickets now. Thanks!
