### ISSUE TITLE
Make sure permalinks are flushed when IssuePress is activated

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/IssuePress#63]
Need to add the following into the plugin activation hook to flush rewrite rules otherwise the IssuePress internal API 404s:

https://codex.wordpress.org/Function_Reference/flush_rewrite_rules

**Comment by issuepressapp** [comment]
I've noticed that my other custom post type templates are 404'ing with IssuePress activated unless I add the flush_rewrite_rules to my cpt. However, that's bad practice, so I'd like to avoid it. The issue appears to be with issuepress

---

IssuePress Data:

username: "joshuadnelson"
email: "josh@joshuadnelson.com"
firstname: "Joshua"
lastname: "Nelson"
display_name: "Joshua Nelson"
ID: "130"
gravatar_id: "5230f4cb66616b0c87d3d50cf3593e63"

Sent via [IssuePress](http://issuepress.co)
