### ISSUE TITLE
Limit IP Sidebars to only accept IP Widgets

### ISSUE THREAD

**Issue by matthewsimo** [LiftUX/IssuePress#65]
& look into available methods to restrict the IP Widgets to only be placed in IP Sidebars (which is actually more important)..

**Comment by matthewsimo** [comment]
Tried, but it's going to take too long to add this sort of functionality, as it's not completely crucial, I think we can push it off beta milestone. Thoughts?

**Comment by garand** [comment]
Yea, I don't think it is critical, especially for beta.

**Comment by matthewsimo** [comment]
Moved to public launch milestone..

**Comment by imbradmiller** [comment]
Sorry I missed this. Yes, that's ok to move for the public launch.

**Comment by imbradmiller** [comment]
Let's make this a lower priority and do this post launch. The notification on the widgets should be fine for now.
