### ISSUE TITLE
Convert layout to mobile-first responsive

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/IssuePress#70]
The layout of IssuePress currently is not mobile-friendly and was implemented with some wonkiness when it comes to being able to customize header text/image and whatnot. 

Let's convert it to be mobile-first so that we have a solid set of base styles to work from. Please create this as a branch so we don't have to delay beta launch this week.

Also, I don't think we need the log out button to be a drop-down. Perhaps we can simplify the login/sign in/sign out area to be more user-friendly and compact without requiring a drop-down.

**Comment by garand** [comment]
@chriswallace Do you have any design ideas for this?

**Comment by chriswallace** [comment]
Be creative.

**Comment by matthewsimo** [comment]
Since this got assigned over to me and I'll have to fully review the scss architecture before I can really convert this to a mobile-first responsive layout I'm going to move this to the "Public Launch" milestone since this isn't beta blocking.

**Comment by matthewsimo** [comment]
Requirements for this is design & css rework. Assigning to @chriswallace for the time being since he was putting together some mocks.

**Comment by imbradmiller** [comment]
Closing this because we are breaking these enhancements all into their own tickets.
