### ISSUE TITLE
Search progress/status icon in search field

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#76]
We need a search progress/status icon in search field when a user searches for a support section/repo.

**Comment by garand** [comment]
@imbradmiller Do you mean a loading icon?

**Comment by imbradmiller** [comment]
Search loading icon, yes.

**Comment by imbradmiller** [comment]
I don't see this in the current install that I just downloaded. Please confirm.

**Comment by matthewsimo** [comment]
This is because you're using an old version, update to latest and reopen if there are still issues you are seeing. Going to close out for time being.
