### ISSUE TITLE
Need to create a new issue widget

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#77]
Need to create a new issue widget

**Comment by matthewsimo** [comment]
Update: We'll add this to the header when in a repo context, otherwise it'll be hidden. Not going widget for this, not for beta at least.

**Comment by garand** [comment]
@matthewsimo Is this completed then?

**Comment by matthewsimo** [comment]
No, I still need to carve time out to add this to the main navigation. I was just updating the ticket to clarify after our meeting @imbradmiller & I had decided to not make a whole new widget, but rather just add it via main nav. Stay tuned.
