### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#8]

**Comment by mattriopelle** [comment]
How do these relate to creating the functional specs? Maybe we should chat about that soon.

**Comment by imbradmiller** [comment]
Matt, I can't handle the functional spec. Just won't get to it today.

**Comment by imbradmiller** [comment]
Done, it's in dropbox here. Dropbox/Lift/Lift/Internal Projects/IssuePress/Discovery/Prototype and also here https://basecamp.com/1761770/projects/1471317-issue-press/messages/8662513-issue-press
