### ISSUE TITLE
Nag message for non-pretty-permalinks sites

### ISSUE THREAD

**Issue by matthewsimo** [LiftUX/IssuePress#83]
permalinks are required, make user super aware

**Comment by matthewsimo** [comment]
I _think_ I've just successfully deployed and pushed out version '1.0.3-beta', this is fixed in this version. Please confirm and close. Thanks!

**Comment by imbradmiller** [comment]
Will review today.

**Comment by imbradmiller** [comment]
Boom, Closed.
