### ISSUE TITLE
IP Options save button

### ISSUE THREAD

**Issue by matthewsimo** [LiftUX/IssuePress#84]
White screen of death on IP Options save in wp admin

**Comment by matthewsimo** [comment]
I _think_ I've just successfully deployed and pushed out version '1.0.3-beta', this should be fixed in this version (and all edge cases that could pop up). Please confirm and close. Thanks!

**Comment by imbradmiller** [comment]
I'll review today.

**Comment by imbradmiller** [comment]
Boom, Done.
