### ISSUE TITLE
Add the ability to add custom fields for Create New Issue Form.

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#87]
It would be really great to be able to create custom fields within the admin of IssuePress that gave additional fields to users creating issues on the front end. We could ~~easily~~ have that content rendered into the GitHub issue description.

**Comment by matthewsimo** [comment]
"easily" might be a stretch, but I like this idea! :) I think it would be a good feature. Though, I think we'd have to think on how to implement it successfully without making it overly complicated for the user or overly complex in the code.

**Comment by imbradmiller** [comment]
Got it. Easily scratched out. ;)
