### ISSUE TITLE
Commenting on a issue breaks the Issue Template.

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#88]
When I comment on an issue it breaks the issue template. The comment is sent to GitHub but it breaks the front end.

**Comment by matthewsimo** [comment]
Probably related to #86 if I had to guess, left over bugs from the org/owner feature addition. Thanks, I'll look into it!

**Comment by matthewsimo** [comment]
I merged a potential fix into trunk, and ran the deploy. Let me know if 1.0.2 shows up for you and fixes this. Thanks

**Comment by imbradmiller** [comment]
Works!
