### ISSUE TITLE
Design concepts based on revised Brad wireframes

### ISSUE THREAD

**Issue by mattriopelle** [LiftUX/IssuePress#9]
Once Brad gets those to you.

**Comment by imbradmiller** [comment]
I'll have these completed and uploaded to basecamp in the monen! (yes I spelled it that way on purpose) http://www.youtube.com/watch?v=YK18wQA-tHs go to 1:35 and you will understand. :+1:

**Comment by imbradmiller** [comment]
Hey @chriswallace did you want to have Anthony just go straight to HTML/CSS with our initial design concept? Anthony offered to get started on that next week and save us from having to do all of the PSD work. I think that's not a bad idea but if you have a reason for not doing that, please let me know.

**Comment by chriswallace** [comment]
Make it so.
—

**Comment by imbradmiller** [comment]
Beautiful. I would have just done it but I remember you mentioning something about having Anthony not focus on any design tasks. Either way, cool beans! 

Schedule it up, @mattriopelle

**Comment by imbradmiller** [comment]
Closing this ticket.
