### ISSUE TITLE
Recent Activity Widget Changes

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#91]
We need to make changes to the recent activity widget prior to beta launch. Those changes are below in the screenshot and noted here.
- Include action
- Include user that completed the action
- Include section/repo that links to the section within IssuePress
- Include last updated date
- Add view button that links to the issue details page
- Add hyperlink to issue title that links to the issue details page

![screen shot 2014-05-01 at 5 25 52 pm](https://cloud.githubusercontent.com/assets/390916/2857398/33173958-d177-11e3-9882-9689bd4d0e94.png)

**Comment by matthewsimo** [comment]
Hey Brad, so I've been working through this stuff and wanted to get your ideas/concept on handling Open/Closed/Reopen events, just noticed they aren't covered in your little wire here.

**Comment by matthewsimo** [comment]
What if we change "Comment added by (user)" to be "(user) (action) on an issue" or "(user) made a comment"? I _think_ that'd handle all the potential cases we want to handle in this,  at least for beta, we can look at it again when we get more data...

Does that sound good? Or do you have any other input?

**Comment by imbradmiller** [comment]
I think that's a good solution, Simo. Let's go with that for now and we can improve later.

**Comment by matthewsimo** [comment]
Ok, I've merged this into master and deployed and updated IP in the EDD interface, you should be showing an update in your install Brad. Once you update, please QA this issue. Thanks.

**Comment by imbradmiller** [comment]
The title doesn't have a style for the link. This is working the way it should, just needs a style.

**Comment by matthewsimo** [comment]
This was a simple fix and was just deployed out. But I'll let you close out once you've updated your local plugin and verified. Thanks, assigning to you @imbradmiller!

**Comment by matthewsimo** [comment]
Did you get a chance to look at this @imbradmiller? If so, let close out. Thanks bud

**Comment by imbradmiller** [comment]
Oh crap, my bad. Let me test now.

**Comment by imbradmiller** [comment]
@matthewsimo so I went into incognito mode and never got the update for the plugin. It's not telling me there is one available and I'm not seeing the fix. Thoughts? I mean don't get me wrong, I believe you. LOL

**Comment by matthewsimo** [comment]
What version are you using at the moment?

On Tue, May 13, 2014 at 10:32 AM, Brad Miller notifications@github.comwrote:

> @matthewsimo https://github.com/matthewsimo so I went into incognito
> mode and never got the update for the plugin. It's not telling me there is
> one available and I'm not seeing the fix. Thoughts? I mean don't get me
> wrong, I believe you. LOL
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/UpThemes/IssuePress/issues/91#issuecomment-42970983
> .

## 
- Matthew Simo

**Comment by imbradmiller** [comment]
1.0.4-Beta, @matthewsimo

**Comment by matthewsimo** [comment]
Hmm, latest is 1.0.7-beta not sure what’s up with EDD or the deploy
script.. stand by. I’ll deploy another version and move to X.X.X format and
see if you get that update...

On Tue, May 13, 2014 at 10:42 AM, Brad Miller notifications@github.comwrote:

> 1.0.4-Beta, @matthewsimo https://github.com/matthewsimo
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/UpThemes/IssuePress/issues/91#issuecomment-42972356
> .

## 
- Matthew Simo

**Comment by imbradmiller** [comment]
Boom!
