### ISSUE TITLE
Search results changes

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#92]
We need to make changes to the search results prior to beta launch. Those changes are below in the screenshot and noted here.
- Include section/repo that links to the section within IssuePress
- Include last updated date
- Change button from 'open' to 'view'
- Add hyperlink to issue title that links to the issue details page

![screen shot 2014-05-01 at 5 30 35 pm](https://cloud.githubusercontent.com/assets/390916/2857455/e4dccf54-d177-11e3-9463-898661bf397b.png)

**Comment by matthewsimo** [comment]
How's this? 

![](http://f.cl.ly/items/1Q3E3F423o3W3r0t2v1o/Screen%20Shot%202014-05-05%20at%203.10.28%20PM.png)

**Comment by imbradmiller** [comment]
Hey, that looks pretty sharp. Let's roll with it.

**Comment by imbradmiller** [comment]
@matthewsimo So this is on my plate to QA correct?

**Comment by matthewsimo** [comment]
This is currently in the modules-revamp branch, once I merge this into master (working on finishing #91 before doing that) and get a deploy pushed you'll be ready to QA. 

I thought I had reassigned it back to me after I had gotten your input, apologies.

**Comment by matthewsimo** [comment]
Ok, I've merged this into master and deployed and updated IP in the EDD interface, you should be showing an update in your install Brad. Once you update, please QA this issue. Thanks.

**Comment by imbradmiller** [comment]
Boom, this looks good.
