### ISSUE TITLE
Readme File for Developer Documentation

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#98]
Make a simple read me file that brings some simple explanation of how to customize the plugin to a users liking. I think this first version will be very minimal.

**Comment by matthewsimo** [comment]
Take a look and make any edits you deem necessary: https://github.com/UpThemes/IssuePress/wiki/Developer-Documentation

**Comment by imbradmiller** [comment]
Wow nice work, Simo. Though I have no clue what any of this means, it looks awesome. @chriswallace please give it a good once over before by tomorrow am.

**Comment by matthewsimo** [comment]
Going to close this out as I think it's satisfactory for the time being and will be an ongoing thing. Thanks!
